package ix.core.models;

import javax.persistence.*;
import be.objectify.deadbolt.core.models.Subject;
import com.fasterxml.jackson.annotation.JsonBackReference;
import ix.core.controllers.AdminFactory;
import ix.core.controllers.PrincipalFactory;
import play.data.validation.Constraints.*;

import java.util.List;

@Entity
// Commented

// @Table(name="ix_core_principal")

// The table name needs to be small, or else it will violate the oracle 30 char
// limit while generating constraints. There is a bug in the DDL generation for
// the oracle driver, so constraints often have 3 extra characters beyond the 
// 30 limit, which seem to be lazily generated by placing "pk_" in front of the
// table name.
//
// This is especially a problem when join tables are used in inheritance (as is
// the case here). Manually overriding the join table name is not apparently 
// possible in such cases.
//
// For example, the principals associated with the ix_ginas_amount would have
// name:
//    "ix_ginas_agentmod_core_princip"
// This is properly truncated to 30 chars. However, the primary key constraint
// is not:
//    "pk_ix_ginas_agentmod_core_princip"
// To guard against this, 'ix_core_principal' needs to be shorter, so this 
// never becomes an issue at truncation.
//
// This is indeed an ugly work-around.
@Table(name="ix_core_principal")
@Inheritance
@DiscriminatorValue("PRI")
public class Principal extends IxModel {
    // provider of this principal
    public String provider; 
    
   // @Required
    @Indexable(facet=true,name="Principal")
    @Column(unique=true)
    public String username;

    @Email
    public String email;
    public boolean admin = false;

    @Column(length=1024)
    public String uri; // can be email or any unique uri

    @ManyToOne(cascade=CascadeType.ALL)
    public Figure selfie;

    public Principal () {}
    public Principal (boolean admin) {
        this.admin = admin;
    }
    public Principal (String email) {
        this.email = email;
    }
    public Principal (boolean admin, String email) {
        this.admin = admin;
        this.email = email;
    }
    public Principal (String username, String email) {
        this.username = username;
        this.email = email;
    }

    public boolean isAdmin () { return admin; }
}
